servers:
  web:
    - 91.98.71.82

accessories:
  db:
    image: postgres:15
    host: 91.98.71.82
    env:
      clear:
        RAILS_ENV: production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    port: 5432

env:
  clear:
    RAILS_ENV: production
  secret:
    - SECRET_KEY_BASE
    - POSTGRES_PASSWORD

proxy:
  ssl: false
  host: 91.98.71.82